# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfea954e60f53a45f29eaf2561b5bc2c1a6e0bd5c6007697a24aa77203ff155428e4a121ecc4843a5b52cdcae8324ad0859c73f40d6f95c9a032f12e44d07233

test:
  secret_key_base: 003d433c092cb76699178c2109da7fd36e250cb0105841fff5caf82a14dfe88d9aa8de47e6c07c0a772e9690895ebec3a70dcab0d0dabb58b0e074a282484788

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
